<?php /* main content */ ?>

<!-- <?php echo "<hr />This is body."; ?> -->

<!-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ -->

<section>
    <br /><br />
    <p>This is "1_main.html" file. This is supposed to show.</p> <!-- delete everything before this -->

    <!-- populate this section with data from a database -->
    
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, a autem modi numquam magnam doloremque et. Sequi rerum beatae voluptates aspernatur nihil, porro, aperiam recusandae dolorum modi, vitae facilis quidem ad eveniet aut tempora laboriosam eligendi similique neque in reprehenderit cupiditate magni tenetur sunt provident? Eius repellat officiis nemo ipsa!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, tenetur mollitia earum debitis est sed a ex? Delectus sapiente repellendus voluptas modi, mollitia at doloribus? Voluptatem tenetur, accusamus fuga enim, laboriosam quos quasi magnam vel ea tempora doloribus nisi numquam ex, assumenda eaque repellat culpa eos. Deleniti culpa ratione quos earum sunt, possimus unde pariatur. Enim, consequatur illo unde doloremque quae non alias sit numquam exercitationem fugiat ea? Sapiente eaque hic et ratione suscipit ducimus quos placeat voluptas sequi sit non a, doloribus deserunt perspiciatis nemo quis, impedit beatae deleniti aut! Aspernatur maxime sed officiis modi. Placeat ipsum laboriosam dolore. Provident dolorem culpa assumenda, beatae sed rerum sapiente quas est fuga quasi asperiores facere omnis, fugiat, consequatur alias odit maxime aut labore suscipit incidunt! Enim omnis beatae nostrum error aliquam obcaecati, alias, corporis non facere, facilis numquam explicabo ea incidunt cumque placeat voluptatibus sequi dicta eum excepturi mollitia magni! Hic?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corporis possimus dolores, harum asperiores rem blanditiis unde nemo veritatis dolorem dolore, maxime impedit neque tempore itaque! Excepturi cupiditate nisi commodi iure maiores ipsa facere expedita, aliquam voluptatem dolor delectus soluta eum, dicta dolorum, ullam debitis natus! Sit eius dolorum qui quisquam. Vero est sed nam excepturi distinctio, veritatis ratione quo, eos explicabo harum quibusdam nihil eligendi pariatur itaque alias cumque odio? Atque quae, earum odio quam doloribus blanditiis perspiciatis aliquam explicabo vel, est dicta maxime asperiores harum rem laudantium exercitationem. Culpa tempora quod iure magnam omnis ea recusandae, minima nostrum ullam ab nulla illum. Omnis quaerat aut iste dicta labore nobis, excepturi possimus sunt nulla commodi hic accusamus animi officiis. At illum autem omnis ullam aliquam ea esse iste, doloribus natus impedit rem atque sed architecto ab mollitia voluptate beatae magni ducimus aspernatur dignissimos! Ratione deleniti sint at assumenda distinctio consectetur impedit, cum rem quos perspiciatis minus architecto praesentium fugiat natus eveniet! Repellat, itaque. Praesentium dignissimos nulla libero ex sapiente. Voluptate nisi hic optio vel sint. Sit beatae libero, dignissimos fuga fugit est voluptas dolores vel debitis ullam illum nisi. Architecto nostrum, accusantium in nihil assumenda asperiores minima magnam exercitationem maiores tenetur qui unde doloribus, ullam optio, rem eligendi velit quam tempora omnis veritatis! Eius harum, recusandae culpa magni soluta, doloribus nemo sit eos, maxime commodi nesciunt veritatis similique cumque inventore autem illo repellendus deserunt. Fugiat illo molestiae quisquam nam suscipit quod ab dolore ipsa, commodi dolorum doloribus. Ab natus suscipit quam earum excepturi rem necessitatibus! Enim, magnam. Qui veritatis iste enim neque corrupti earum ducimus repellendus cum aperiam delectus sapiente quo, aliquid iusto totam rem quibusdam architecto voluptatem eveniet esse doloremque omnis, iure natus voluptatum. Quaerat, veniam quibusdam ab vel, aut vero, neque eius doloremque nulla animi cumque error quos?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, tenetur mollitia earum debitis est sed a ex? Delectus sapiente repellendus voluptas modi, mollitia at doloribus? Voluptatem tenetur, accusamus fuga enim, laboriosam quos quasi magnam vel ea tempora doloribus nisi numquam ex, assumenda eaque repellat culpa eos. Deleniti culpa ratione quos earum sunt, possimus unde pariatur. Enim, consequatur illo unde doloremque quae non alias sit numquam exercitationem fugiat ea? Sapiente eaque hic et ratione suscipit ducimus quos placeat voluptas sequi sit non a, doloribus deserunt perspiciatis nemo quis, impedit beatae deleniti aut! Aspernatur maxime sed officiis modi. Placeat ipsum laboriosam dolore. Provident dolorem culpa assumenda, beatae sed rerum sapiente quas est fuga quasi asperiores facere omnis, fugiat, consequatur alias odit maxime aut labore suscipit incidunt! Enim omnis beatae nostrum error aliquam obcaecati, alias, corporis non facere, facilis numquam explicabo ea incidunt cumque placeat voluptatibus sequi dicta eum excepturi mollitia magni! Hic?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, a autem modi numquam magnam doloremque et. Sequi rerum beatae voluptates aspernatur nihil, porro, aperiam recusandae dolorum modi, vitae facilis quidem ad eveniet aut tempora laboriosam eligendi similique neque in reprehenderit cupiditate magni tenetur sunt provident? Eius repellat officiis nemo ipsa!</p>

</section>

<aside>
        <!-- populate this section with data from a database -->
</aside>

<!-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ -->